#!/usr/bin/env python3
import argparse, subprocess, sys, json
from pathlib import Path

src_path = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(src_path))

CONFIG_FILE = Path(".dissmob_config.json")
DEFAULT_CONFIG = {
    "input_dir": "latex/mobile/md",
    "output_dir": "latex/mobile/tex",
    "staging_file": "latex/mobile/input_lines.tex"
}

# -------------------- Init --------------------
def init_project():
    print("Default directory structure:\n"
          "latex/mobile/\n"
          "├── md/           # raw markdown drafts\n"
          "├── tex/          # converted TeX outputs\n"
          "└── input_lines.tex   # \\input{} staging file\n")
    ans = input("Accept this default? [Y/n]: ").strip().lower()
    
    cfg = DEFAULT_CONFIG.copy()
    if ans == "n":
        cfg["input_dir"] = input("Enter path for input (Markdown drafts): ").strip()
        cfg["output_dir"] = input("Enter path for output (TeX files): ").strip()
        cfg["staging_file"] = input("Enter path for staging file: ").strip()

    save_config(cfg)

    # Create directories
    Path(cfg["input_dir"]).mkdir(parents=True, exist_ok=True)
    Path(cfg["output_dir"]).mkdir(parents=True, exist_ok=True)
    Path(cfg["staging_file"]).parent.mkdir(parents=True, exist_ok=True)
    if not Path(cfg["staging_file"]).exists():
        Path(cfg["staging_file"]).write_text("% Auto-generated by dissmob\n")

    print("Project initialized with config:")
    print(json.dumps(cfg, indent=2))

def load_config():
    if not CONFIG_FILE.exists():
        print("Config not found. Run `dissmob --init` first.")
        sys.exit(1)
    return json.loads(CONFIG_FILE.read_text())

def save_config(cfg):
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))

# -------------------- Conversion --------------------
def convert_file(name, cfg, force=False, box=False):
    md_file = Path(cfg["input_dir"]) / f"{name}.md"
    tex_file = Path(cfg["output_dir"]) / f"{name}.tex"

    if not md_file.exists():
        print(f"Markdown file not found: {md_file}")
        return

    if tex_file.exists() and tex_file.stat().st_mtime > md_file.stat().st_mtime and not force:
        print(f"Skipping {name} (up-to-date)")
        return

    tex_file.parent.mkdir(parents=True, exist_ok=True)

    cmd = ["pandoc", str(md_file), "-o", str(tex_file)]
    subprocess.run(cmd, check=True)

    # Provisional boxing
    if box:
        content = tex_file.read_text()
        boxed_content = (
            "\\begin{tcolorbox}[colframe=red!60!black,title=Mobile Draft]\n"
            + content +
            "\n\\end{tcolorbox}\n"
        )
        tex_file.write_text(boxed_content)

    print(f"Converted {md_file} → {tex_file}")

    # Update input_lines.tex
    staging_file = Path(cfg["staging_file"])
    input_line = f"\\input{{{cfg['output_dir']}/{name}}} % from {name}.md\n"

    # Read existing lines and avoid duplicates
    lines = staging_file.read_text().splitlines()
    lines = [l for l in lines if name not in l]  # remove old line for same file
    lines.append(input_line)
    staging_file.write_text("\n".join(lines) + "\n")

    # Print input line for convenience
    print(input_line.strip())

# -------------------- Bulk conversion --------------------
def bulk_convert(cfg, force=False, box=False):
    md_files = Path(cfg["input_dir"]).glob("*.md")
    for md in md_files:
        convert_file(md.stem, cfg, force=force, box=box)

# -------------------- Main --------------------
def main():
    parser = argparse.ArgumentParser(description="Mobile Markdown → LaTeX pipeline")
    parser.add_argument("filename", nargs="?", help="Name of the draft (without extension)")
    parser.add_argument("--init", action="store_true", help="Initialize project (config + dirs)")
    parser.add_argument("--force", "-f", action="store_true", help="Force rebuild even if up-to-date")
    parser.add_argument("--box", "-b", action="store_true", help="Wrap output in red tcolorbox (provisional)")
    args = parser.parse_args()

    if args.init:
        init_project()
        return

    cfg = load_config()

    if args.filename:
        convert_file(args.filename, cfg, force=args.force, box=args.box)
    else:
        bulk_convert(cfg, force=args.force, box=args.box)

            # After pandoc converts MD -> TeX
    for tmp_tex_path in Path(cfg['output_dir']).glob('*.tex'):
        with open(tmp_tex_path, "r", encoding="utf-8") as f:
            tex_content = f.read()
        tex_content = tex_content.replace("\\tightlist", "")
        with open(tmp_tex_path, "w", encoding="utf-8") as f:
            f.write(tex_content)
    
if __name__ == "__main__":
    main()
